language: julia
os:
  - linux
  - osx
julia:
  - 1.0
  - latest
  - nightly
notifications:
  email: false
# script:
#   - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#   - julia -e 'import Pkg; Pkg.clone("https://github.com/dcjones/Codecs.jl"); Pkg.clone("https://github.com/dcjones/YAML.jl"); Pkg.clone(pwd(), "openBF"); Pkg.build("openBF"); Pkg.test("openBF"; coverage=true)'
after_success:
  - julia -e 'using Pkg; cd(Pkg.dir("openBF")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
matrix:
  fast_finish: true
