language: julia
os:
  - linux
  - osx
julia:
  - 0.4
  - 0.5
  - 0.6
  - nightly
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  # - julia -e 'Pkg.clone("https://github.com/INSIGNEO/openBF.git")'
  # - cd test/
  # - julia --code-coverage runtests.jl
  # - cd ../
  - julia -e 'Pkg.clone(pwd(), "openBF"); Pkg.build("openBF"); Pkg.test("openBF"; coverage=true)'
after_success:
  - echo "done!"
  - julia -e 'cd(Pkg.dir("openBF")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
matrix:
  fast_finish: true
  allow_failures:
    - julia: nightly, 0.4, 0.5
    - os: osx, linux
