language: julia
os:
  - linux
julia:
  - 0.6
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone(pwd())'
  - mkdir -p ~/.julia/v0.6/openBF
  - cp -r src ~/.julia/v0.6/openBF/
  - mkdir -p ~/.julia/v0.6/BTypes/src
  - cp src/BTypes.jl ~/.julia/v0.6/BTypes/src/
  - cd test/
  - julia --code-coverage runtests.jl
after_success:
  - echo "done!"
  # - julia -e 'cd(Pkg.dir("openBF")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
  # - bash <(curl -s https://codecov.io/bash) -t e6644b12-b397-49be-8f79-16c59a3a9S
